# -*- coding: utf-8 -*-
"""IDP Group 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tIuzskvxaRn1dJx0IhM8-Mhy2rpNGHAk
"""

#Import Libraries
from typing import Optional, Any
import warnings
from tifffile import TiffFile, TiffWriter
import numpy as np
import matplotlib.pyplot as plt
from skimage.transform import resize
import tensorflow as tf

def read_stiff(filename: str, silent=False, rgb_only=False):
    """

    :param filename:    filename of the spectral tiff to read.
    :return:            Tuple[spim, wavelengths, rgb, metadata], where
                        spim: spectral image cube of form [height, width, bands],
                        wavelengths: the center wavelengths of the bands,
                        rgb: a color render of the spectral image [height, width, channels] or None
                        metadata: a free-form metadata string stored in the image, or an empty string
    """
    TIFFTAG_WAVELENGTHS = 65000
    TIFFTAG_METADATA = 65111
    spim = None
    wavelengths = None
    rgb = None
    metadata = None

    first_band_page = 0
    with TiffFile(filename) as tiff:
        # The RGB image is optional, the first band image maybe on the first page:
        first_band_page = 0
        if tiff.pages[first_band_page].ndim == 3:
            rgb = tiff.pages[0].asarray()
            # Ok, the first band image is on the second page
            first_band_page = first_band_page + 1

        multiple_wavelength_lists = False
        multiple_metadata_fields = False
        for band_page in range(first_band_page, len(tiff.pages)):
            # The wavelength list is supposed to be on the first band image.
            # The older write_tiff writes it on all pages, though, so make
            # a note of it.
            tag = tiff.pages[band_page].tags.get(TIFFTAG_WAVELENGTHS)
            tag_value = tag.value if tag else tuple()
            if tag_value:
                if wavelengths is None:
                    wavelengths = tag_value
                elif wavelengths == tag_value:
                    multiple_wavelength_lists = True
                elif wavelengths != tag_value:
                    # Well, the image is just broken then?
                    raise RuntimeError(f'Spectral-Tiff "{filename}" contains multiple differing wavelength lists!')

            # The metadata string, like the wavelength list, is supposed to be
            # on the first band image. The older write_tiff wrote it on all
            # pages, too. Make a note of it.
            tag = tiff.pages[band_page].tags.get(TIFFTAG_METADATA)
    
            tag_value = tag.value if tag else ''
            if tag_value:
                if metadata is None:
                    metadata = tag_value
                elif metadata == tag_value:
                    multiple_metadata_fields = True
                elif metadata != tag_value:
                    # Well, for some reason there are multiple metadata fields
                    # with varying content. This version of the function does
                    # not care for such fancyness.
                    raise RuntimeError(f'Spectral-Tiff "{filename}" contains multiple differing metadata fields!')

        # The metadata is stored in an ASCII string. It may contain back-slashed
        # hex sequences (unicode codepoints presented as ASCII text). Convert
        # ASCII string back to bytes and decode as unicode sequence.
        if metadata:
            metadata = metadata.encode('ascii').decode('unicode-escape')
        else:
            metadata = ''

        # Some of the early images may have errorneus metadata string.
        # Attempt to fix it:
        if len(metadata) >= 2 and metadata[0] == "'" and metadata[-1] == "'":
            while metadata[0] == "'":
                metadata = metadata[1:]
            while metadata[-1] == "'":
                metadata = metadata[:-1]
            if '\\n' in metadata:
                metadata = metadata.replace('\\n', '\n')

        # Generate a fake wavelength list, if the spectral tiff has managed to
        # lose its own wavelength list.
        if not wavelengths:
            wavelengths = range(0, len(tiff.pages) - 1 if rgb is not None else len(tiff.pages))

        if multiple_wavelength_lists and not silent:
            warnings.warn(f'Spectral-Tiff "{filename}" contains duplicated wavelength lists!')
        if multiple_metadata_fields and not silent:
            warnings.warn(f'Spectral-Tiff "{filename}" contains duplicated metadata fields!')

        if not rgb_only:
            spim = tiff.asarray(key=range(first_band_page, len(tiff.pages)))
            spim = np.transpose(spim, (1, 2, 0))
        else:
            spim = None

        # Make sure the wavelengths are in an ascending order:
        if wavelengths[0] > wavelengths[-1]:
            spim = spim[:, :, ::-1] if spim is not None else None
            wavelengths = wavelengths[::-1]

    # Convert uint16 cube back to float32 cube
    if spim is not None and spim.dtype == 'uint16':
        spim = spim.astype('float32') / (2**16 - 1)

    return spim, np.array(wavelengths), rgb, metadata

def read_mtiff(filename):
    """
    Read a mask bitmap tiff.

    Mask bitmap tiff contains multiple pages of bitmap masks. The mask label
    is stored in tag 65001 in each page. The mask label is stored as an ASCII
    string that may contain unicode codepoints encoded as ASCII character
    sequences (see unicode-escape encoding in Python docs).

    :param filename:    filename of the mask tiff to read.
    :return:            Dict[label: str, mask: ndarray], where
                        label: the mask label
                        mask: the boolean bitmap associated with the label.
    """
    TIFFTAG_MASK_LABEL = 65001
    masks = dict()
    with TiffFile(filename) as tiff:
        for p in range(0, len(tiff.pages)):
            label_tag = tiff.pages[p].tags.get(TIFFTAG_MASK_LABEL)
            if label_tag is None:
                if p > 0:
                    print(f'** page {p}: no TIFF_MASK_LABEL tag. Ignored.')
                continue
            label = label_tag.value.encode('ascii').decode('unicode-escape')
            mask = tiff.asarray(key=p)
            masks[label] = mask > 0
    return masks

def getLabelCode(label_name, classes):
  if not label_name in classes:
      classes.append(label_name) 
  return classes.index(label_name)

IMAGE_SIZE=128
IMAGE_CHANNELS = 38
def getUnetModel(n_classes):
  inputs = tf.keras.layers.Input((IMAGE_SIZE,IMAGE_SIZE,IMAGE_CHANNELS))
  #s = tf.keras.layers.Lambda(lambda x: x/255)(inputs)

  c1 = tf.keras.layers.Conv2D(16,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(inputs)
  c1 = tf.keras.layers.Dropout(0.1)(c1)
  c1 = tf.keras.layers.Conv2D(16,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(c1)
  p1 = tf.keras.layers.MaxPooling2D((2,2))(c1)

  c2 = tf.keras.layers.Conv2D(32,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(p1)
  c2 = tf.keras.layers.Dropout(0.1)(c2)
  c2 = tf.keras.layers.Conv2D(32,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(c2)
  p2 = tf.keras.layers.MaxPooling2D((2,2))(c2)

  c3 = tf.keras.layers.Conv2D(64,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(p2)
  c3 = tf.keras.layers.Dropout(0.1)(c3)
  c3 = tf.keras.layers.Conv2D(64,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(c3)
  p3 = tf.keras.layers.MaxPooling2D((2,2))(c3)

  c4 = tf.keras.layers.Conv2D(128,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(p3)
  c4 = tf.keras.layers.Dropout(0.2)(c4)
  c4 = tf.keras.layers.Conv2D(128,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(c4)
  p4 = tf.keras.layers.MaxPooling2D(pool_size=(2,2))(c4)

  c5 = tf.keras.layers.Conv2D(256,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(p4)
  c5 = tf.keras.layers.Dropout(0.3)(c5)
  c5 = tf.keras.layers.Conv2D(256,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(c5)

  #Expansive path
  u6 = tf.keras.layers.Conv2DTranspose(128,(2,2),strides=(2,2),padding="same")(c5)
  u6 = tf.keras.layers.concatenate([u6,c4])
  c6 = tf.keras.layers.Conv2D(128,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(u6)
  c6 = tf.keras.layers.Dropout(0.2)(c6)
  c6 = tf.keras.layers.Conv2D(128,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(c6)

  u7 = tf.keras.layers.Conv2DTranspose(64,(2,2),strides=(2,2),padding="same")(c6)
  u7 = tf.keras.layers.concatenate([u7,c3])
  c7 = tf.keras.layers.Conv2D(64,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(u7)
  c7 = tf.keras.layers.Dropout(0.2)(c7)
  c7 = tf.keras.layers.Conv2D(64,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(c7)

  u8 = tf.keras.layers.Conv2DTranspose(32,(2,2),strides=(2,2),padding="same")(c7)
  u8 = tf.keras.layers.concatenate([u8,c2])
  c8 = tf.keras.layers.Conv2D(32,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(u8)
  c8 = tf.keras.layers.Dropout(0.1)(c8)
  c8 = tf.keras.layers.Conv2D(32,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(c8)

  u9 = tf.keras.layers.Conv2DTranspose(16,(2,2),strides=(2,2),padding="same")(c8)
  u9 = tf.keras.layers.concatenate([u9,c1])
  c9 = tf.keras.layers.Conv2D(16,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(u9)
  c9 = tf.keras.layers.Dropout(0.1)(c9)
  c9 = tf.keras.layers.Conv2D(16,(3,3), activation="relu", kernel_initializer="he_normal",padding="same")(c9)

  outputs  = tf.keras.layers.Conv2D(n_classes, (1,1), activation="softmax")(c9)
  model = tf.keras.Model(inputs=[inputs], outputs=[outputs])
  return model

# from google.colab import drive
# drive.mount('/content/idp')


annotation_file_name = "annotation.npy"
class_colors = np.array([[0,0,0],[255,0,0],[255,255,0],[0,234,255],[170,0,255],[255,127,0],[0,149,255],
                  [255,0,170],[106,255,0],[0,64,255],[35,98,143],[143,106,35]])




#model = getUnetModel(len(classes))
#model.compile(optimizer="adam", loss="categorical_crossentropy",metrics=["accuracy"],sample_weight_mode="temporal")
#model.summary()




